image: openjdk:11.0.8-jdk-slim-buster

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script: ./gradlew --build-cache clean build publish
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - build
      - buildSrc/.gradle
      - buildSrc/build
      - .gradle
      - node_modules