[versions]
kotlin = "1.8.10"
coroutines = "1.7.1"
node = "17.3.0"
nodeGradle = "2.2.0"
plantUml = "1.2022.6"
pebble = "3.2.1"
mockito = "4.0.0"
kotest = "5.5.5"
junitPlatform = "1.8.2"
junitJupiter = "5.8.2"
assertJ = "3.22.0"
hamcrest = "1.3"
awaitility = "4.0.3"
minimalJson = "0.9.5"
antlr = "4.13.0"
nexusStaging = "0.30.0"

[libraries]
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin"}
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin"}
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
antlr = { module = "org.antlr:antlr4", version.ref = "antlr"}
assertJCore = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
hamcrestCore = { module = "org.hamcrest:hamcrest-core", version.ref = "hamcrest" }
awaitilityKotlin = { module = "org.awaitility:awaitility-kotlin", version.ref = "awaitility" }
minimalJson = { module = "com.eclipsesource.minimal-json:minimal-json", version.ref = "minimalJson" }
plantuml = { module = "net.sourceforge.plantuml:plantuml", version.ref = "plantUml" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }
kotestAssertionsCoreJvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
junitPlatformTestKit = { module = "org.junit.platform:junit-platform-testkit", version.ref = "junitPlatform" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nodeGradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
nexusStaging = { id = "io.codearte.nexus-staging", version.ref = "nexusStaging" }
