<project>
  <dependencies>
    <dependency>
      <groupId>dev.kensa</groupId>
      <artifactId>kensa-framework-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.kotest</groupId>
      <artifactId>kotest-assertions-core-jvm</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
