name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'kensa.dev/**'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'kensa.dev/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache JavaScript Build Output
        uses: actions/cache@v4
        env:
          cache-name: cache-js-output
        with:
          path: ./ui/build/js
          key: ${{ runner.os }}-build-output-${{ env.cache-name }}-${{ hashFiles('./ui/package-lock.json', './ui/src/**', './ui/public/**') }}
          restore-keys: |
            ${{ runner.os }}-build-output-${{ env.cache-name }}-
      - name: Cache Node Modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ./ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./ui/package-lock.json', './ui/vite.config.js') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
      - name: Build Go CLI
        run: |
          cd cli
          go mod tidy
          mkdir -p build/bin
          go build -o build/bin/kensa cmd/kensa/main.go
      - name: Build
        run: make build-ci
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Tag If Release
        run: make tag-if-release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}