name: Publish Artifacts
on:
  push:
    tags:
      - '*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID  }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY  }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD  }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME  }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD  }}

jobs:
  PublishToStaging:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.ref, '-SNAPSHOT') }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish to Sonatype
        run: make publish-to-sonatype
  PublishToSnapshot:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.ref, '-SNAPSHOT') }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish to Sonatype Snapshot
        run: make publish-to-sonatype-snapshot
  DispatchReleaseEvent:
    runs-on: ubuntu-latest
    needs: [PublishToStaging, PublishToSnapshot]
    if: ${{ always() && (needs.PublishToStaging.result == 'success' || needs.PublishToSnapshot.result == 'success') }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Dispatch Release Event
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: kensa-dev/kensa
          event-type: kensa-release
          client-payload: '{"version": "${{ steps.tagName.outputs.tag }}"}'
